// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: [
  //       '01-getting-started/welcome',
  //       '01-getting-started/how-to-use',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Basics of Social Interaction',
  //     items: [
  //       '02-basics/small-talk',
  //       '02-basics/body-language',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'College & Academic Life',
  //     items: [
  //       '03-college/classroom-etiquette',
  //       '03-college/communicating-with-professors',
  //     ],
  //   },
  // ],
};

export default sidebars;
